INSERT INTO sexual_preferences (user_id, gender_id) VALUES
(1,	1),
(2,	3),
(3,	2),
(4,	3),
(5,	2),
(6,	3),
(7,	2),
(8,	3),
(9,	1),
(10, 1),
(11, 1),
(12, 1),
(13, 1),
(14, 1),
(15, 1),
(16, 1),
(17, 1),
(18, 1),
(19, 1),
(20, 1),
(21, 1),
(22, 1),
(23, 1),
(24, 1),
(25, 1),
(26, 1),
(27, 1),
(28, 1),
(29, 1),
(30, 2),
(31, 2),
(32, 2),
(33, 2),
(34, 2),
(35, 2),
(36, 2),
(37, 2),
(38, 2),
(39, 2),
(40, 2);

INSERT INTO users (email, name, password, age, points, bio, city, gender_id, image_url, is_looking) VALUES
('mahalia@daregleason.name', 'Teri', 'password', 40, 518, 'Kogi gentrify cred godard vhs. Cray wolf tilde pabst. Echo pinterest bespoke lomo next level seitan chia listicle. Fingerstache vinegar marfa park locavore bitters artisan. Actually vinyl offal try-hard next level thundercats.', 'Montreal', 2, 'https://randomuser.me/api/portraits/women/34.jpg', TRUE),
('maybell_gorczany@schulistbrekke.biz', 'Corey', 'password', 32, 344, '90s intelligentsia pop-up before they sold out try-hard vinyl. Ramps photo booth five dollar toast. Umami mumblecore master pop-up. You probably havent heard of them chia echo hammock lo-fi tattooed sustainable. Kickstarter salvia vhs microdosing 3 wolf moon church-key cold-pressed irony. Meggings messenger bag next level asymmetrical bushwick wayfarers selvage kogi.', 'Toronto', 3, 'https://randomuser.me/api/portraits/men/40.jpg', TRUE),
('tobias_frami@schuppewelch.info', 'Curtis', 'password', 23, 17, 'Butcher meditation mixtape etsy celiac lo-fi selfies fashion axe. Health biodiesel chambray cronut gentrify crucifix. Bespoke ethical kombucha. Leggings before they sold out gentrify asymmetrical wayfarers. Flannel slow-carb hammock austin art party tofu.', 'Toronto', 2, 'https://randomuser.me/api/portraits/men/3.jpg', TRUE),
('dianna@schroeder.io', 'Maximo', 'password', 23, 880, 'Selvage cliche crucifix try-hard hoodie meditation. Tote bag quinoa polaroid everyday mixtape. Meditation craft beer tilde. Flannel mlkshk wes anderson occupy pop-up poutine semiotics.', 'Montreal', 1, 'https://randomuser.me/api/portraits/men/46.jpg', TRUE),
('billy.sawayn@schroeder.io', 'Quintin', 'password', 21, 337, 'Typewriter art party +1 tofu tousled biodiesel. Pork belly franzen pug mumblecore williamsburg shoreditch 8-bit everyday. Banjo viral meditation pork belly whatever vhs. Fixie etsy selvage typewriter xoxo. Lumbersexual pickled heirloom small batch waistcoat hoodie trust fund. Tumblr selvage chicharrones tote bag.', 'Quebec City', 3, 'https://randomuser.me/api/portraits/men/77.jpg', TRUE),
('madie.farrell@douglasreilly.net', 'Carlena', 'password', 36, 723, 'Pbr&b dreamcatcher swag tumblr brooklyn austin. Diy ramps single-origin coffee jean shorts humblebrag pickled messenger bag. Hoodie cronut portland you probably havent heard of them cray. Tousled drinking 8-bit.', 'Quebec City', 1, 'https://randomuser.me/api/portraits/women/79.jpg', TRUE),
('julene_will@lesch.co', 'Irina', 'password', 26, 737, '+1 cornhole whatever. Waistcoat literally bicycle rights selvage sartorial try-hard. Vhs bicycle rights quinoa. Irony deep v hashtag wes anderson.', 'Quebec City', 3, 'https://randomuser.me/api/portraits/women/7.jpg', TRUE),
('matt@oconner.co', 'Roberto', 'password', 34, 997, 'Wes anderson readymade direct trade pork belly meggings kombucha austin jean shorts. Tacos master tilde five dollar toast mustache chia butcher swag. Quinoa brooklyn small batch pinterest. Church-key photo booth skateboard wes anderson post-ironic ramps mlkshk biodiesel. Pbr&b brooklyn chicharrones artisan keffiyeh heirloom umami kombucha.', 'Toronto', 3, 'https://randomuser.me/api/portraits/men/57.jpg', TRUE),
('roosevelt@purdyhamill.org', 'Paul', 'password', 19, 150, 'Art party raw denim pinterest. Iphone heirloom etsy chartreuse cold-pressed. Microdosing hashtag ramps vice normcore. Banjo put a bird on it thundercats. Actually blog venmo chambray tilde schlitz health. Migas schlitz thundercats kombucha.', 'Toronto', 3, 'https://randomuser.me/api/portraits/women/8.jpg', TRUE),
('barton.beier@ward.name', 'Edmond', 'password', 30, 246, 'Street small batch chicharrones intelligentsia raw denim farm-to-table. Xoxo yolo fingerstache. Franzen single-origin coffee fixie hashtag disrupt bicycle rights park. Portland crucifix raw denim narwhal lomo sartorial.', 'Toronto', 1, 'https://randomuser.me/api/portraits/men/39.jpg', TRUE),
('heath@wisozk.org', 'Milo', 'password', 40, 99, 'Meggings echo marfa. Gastropub mixtape meh shoreditch roof sartorial cronut. Whatever yolo pinterest kale chips iphone retro beard. Diy chia xoxo. Pinterest fixie roof slow-carb. Gastropub direct trade authentic park pug asymmetrical.', 'Toronto', 1, 'https://randomuser.me/api/portraits/men/21.jpg', TRUE),
('erna.langworth@smithamcremin.info', 'John', 'password', 38, 625, 'Deep v scenester wayfarers keffiyeh skateboard gentrify shoreditch lomo. Poutine crucifix thundercats hoodie. Master vegan vhs park. Butcher cray kitsch tousled. Sartorial scenester phlogiston kickstarter freegan. Venmo etsy actually.', 'Toronto', 1, 'https://randomuser.me/api/portraits/men/36.jpg', TRUE),
('everett.schoen@hahn.org', 'Augustus', 'password', 28, 10, '3 wolf moon migas actually food truck fixie. Plaid poutine taxidermy bicycle rights. Artisan occupy raw denim art party marfa vegan craft beer flannel. Pug single-origin coffee mustache pitchfork humblebrag chicharrones goth cleanse.', 'Montreal', 2, 'https://randomuser.me/api/portraits/women/83.jpg', TRUE),
('elbert@buckridgekihn.info', 'Nancy', 'password', 22, 353, 'Vegan kombucha forage waistcoat bushwick pour-over kickstarter polaroid. Etsy tattooed vinyl forage. Taxidermy artisan cornhole raw denim lo-fi. Salvia chia crucifix. Ennui photo booth next level. Distillery keytar selvage.', 'Toronto', 1, 'https://randomuser.me/api/portraits/women/61.jpg', TRUE),
('india@fritschhowell.org', 'Hortense', 'password', 40, 569, 'Pinterest art party bitters. Semiotics migas raw denim 3 wolf moon try-hard cray tousled xoxo. Kickstarter flexitarian waistcoat chambray gastropub. Disrupt health small batch pop-up meditation pork belly gluten-free farm-to-table. Cold-pressed art party polaroid bicycle rights salvia church-key selfies +1. Five dollar toast tousled offal crucifix fingerstache mixtape.', 'Montreal', 2, 'https://randomuser.me/api/portraits/men/42.jpg', TRUE),
('jeanett@sanford.org', 'Jona', 'password', 39, 900, 'Forage chia truffaut neutra kickstarter health. +1 literally gastropub leggings tattooed. Polaroid franzen lomo. Ethical loko iphone blog whatever sriracha retro chambray. Vice post-ironic fixie semiotics franzen kombucha microdosing. Carry humblebrag tofu ethical health seitan tousled chartreuse.', 'Toronto', 1, 'https://randomuser.me/api/portraits/men/67.jpg', TRUE),
('mona.rolfson@kulas.name', 'Bennie', 'password', 40, 119, 'Vinyl retro raw denim paleo. Godard sustainable leggings pickled wayfarers muggle magic. Beard put a bird on it semiotics vinyl bicycle rights selvage xoxo. Wayfarers mixtape microdosing pinterest deep v craft beer jean shorts tousled.', 'Montreal', 3, 'https://randomuser.me/api/portraits/men/34.jpg', TRUE),
('jee_sipes@feeney.net', 'Jed', 'password', 32, 79, 'Mlkshk thundercats deep v. Narwhal shoreditch hashtag jean shorts single-origin coffee diy stumptown. Keytar 90s thundercats yuccie. Fingerstache pinterest chartreuse kale chips cronut squid ethical cornhole.', 'Quebec City', 3, 'https://randomuser.me/api/portraits/women/33.jpg', TRUE),
('emory@bartonbradtke.net', 'Susanna', 'password', 37, 889, 'Bitters authentic retro flannel meditation brunch. Kombucha meh vinegar drinking salvia. Locavore kitsch irony lumbersexual brooklyn. Semiotics venmo cred shoreditch viral. Dreamcatcher brooklyn asymmetrical.', 'Montreal', 3, 'https://randomuser.me/api/portraits/men/49.jpg', TRUE),
('sau_brakus@oconner.info', 'Lashaunda', 'password', 38, 708, 'Hoodie master microdosing asymmetrical irony raw denim flannel quinoa. Hella scenester five dollar toast portland locavore carry tofu. Pitchfork swag viral twee five dollar toast synth tofu lumbersexual. Asymmetrical mlkshk pitchfork pbr&b artisan. Yr cred hashtag street helvetica locavore pinterest tattooed. Lumbersexual vinegar flexitarian diy selvage taxidermy.', 'Montreal', 3, 'https://randomuser.me/api/portraits/men/18.jpg', TRUE),
('harley_paucek@ryan.org', 'Vonda', 'password', 22, 141, 'Ennui deep v tousled everyday cleanse knausgaard. Tofu hoodie mlkshk. Kinfolk deep v skateboard 90s. Slow-carb kogi wayfarers tacos cliche messenger bag. Schlitz roof organic banjo leggings.', 'Montreal', 1, 'https://randomuser.me/api/portraits/men/52.jpg', TRUE),
('mitchel_prosacco@hegmann.net', 'Santiago', 'password', 20, 638, 'Cray yuccie art party selfies meditation sartorial swag. Mlkshk venmo neutra shoreditch vinegar. Trust fund yolo drinking listicle ugh. Master vinyl taxidermy ennui.', 'Montreal', 3, 'https://randomuser.me/api/portraits/men/93.jpg', TRUE),
('beckie.fahey@zieme.io', 'Joan', 'password', 21, 110, 'Next level taxidermy meggings hella retro pabst locavore. Portland mixtape biodiesel. Polaroid lumbersexual fingerstache park health single-origin coffee. Freegan venmo church-key twee kale chips mumblecore pour-over.', 'Toronto', 2, 'https://randomuser.me/api/portraits/men/26.jpg', TRUE),
('sal@ritchietromp.co', 'Lynn', 'password', 29, 99, 'Church-key letterpress health waistcoat chartreuse. Muggle magic normcore try-hard. Umami distillery cronut squid xoxo small batch +1. Single-origin coffee pabst etsy hammock brunch hashtag before they sold out kogi. Sriracha deep v iphone chartreuse. Brunch chartreuse plaid slow-carb kitsch.', 'Toronto', 1, 'https://randomuser.me/api/portraits/women/47.jpg', TRUE),
('ludie_feest@king.io', 'Azzie', 'password', 19, 333, 'Skateboard park actually waistcoat bitters occupy. Knausgaard muggle magic yolo swag ugh mlkshk trust fund. Seitan occupy banh mi tacos craft beer pinterest paleo vhs. Keytar austin yolo diy pour-over pork belly. Waistcoat cornhole shabby chic twee wes anderson farm-to-table.', 'Toronto', 2, 'https://randomuser.me/api/portraits/men/13.jpg', TRUE),
('arnold@brown.name', 'Daniel', 'password', 24, 511, 'Organic whatever forage. Bushwick knausgaard gentrify vinyl tumblr plaid pickled gastropub. Quinoa shabby chic craft beer blue bottle. Kogi trust fund hoodie biodiesel butcher.', 'Quebec City', 1, 'https://randomuser.me/api/portraits/men/84.jpg', TRUE),
('edison@rutherford.io', 'Aiko', 'password', 30, 193, 'Neutra austin tacos humblebrag roof yolo. Leggings wolf jean shorts post-ironic next level +1. Retro stumptown fashion axe pop-up. Butcher helvetica venmo pour-over tattooed cliche. Beard lomo vice health ugh.', 'Montreal', 2, 'https://randomuser.me/api/portraits/women/81.jpg', TRUE),
('guadalupe_little@jacobi.info', 'Cleo', 'password', 24, 134, 'Mustache tote bag shabby chic. Mustache leggings kinfolk gentrify austin tattooed semiotics. Try-hard irony fixie. Semiotics kitsch organic distillery godard migas. Chia venmo tattooed paleo. Authentic pork belly skateboard gentrify freegan tilde banjo.', 'Toronto', 1, 'https://randomuser.me/api/portraits/men/33.jpg', TRUE),
('lillie@wiza.org', 'Janita', 'password', 23, 280, 'Pabst tote bag typewriter helvetica xoxo schlitz gastropub. Five dollar toast ennui pour-over. Crucifix forage authentic microdosing master. Put a bird on it +1 cornhole freegan irony tote bag kombucha deep v. Marfa irony farm-to-table brunch portland.', 'Montreal', 2, 'https://randomuser.me/api/portraits/women/0.jpg', TRUE),
('salley.watsica@heel.name', 'Elisha', 'password', 24, 610, 'Ennui chambray street small batch pitchfork. Bicycle rights diy muggle magic ramps bespoke. Knausgaard yolo pabst vegan. Humblebrag hoodie gentrify park migas cold-pressed tote bag.', 'Quebec City', 1, 'https://randomuser.me/api/portraits/men/11.jpg', TRUE),
('cayla@kuphal.io', 'Oneida', 'password', 40, 539, 'Portland vice cleanse fashion axe migas. Try-hard viral shabby chic semiotics. Lomo cray plaid deep v tacos 3 wolf moon hella. Knausgaard health cray fanny pack cardigan fashion axe. Farm-to-table franzen pabst williamsburg hashtag messenger bag. Street hoodie church-key fashion axe 90s blue bottle before they sold out helvetica.', 'Montreal', 2, 'https://randomuser.me/api/portraits/men/86.jpg', TRUE),
('louvenia.schaefer@thiel.co', 'Chester', 'password', 38, 503, 'Readymade marfa pug shabby chic normcore asymmetrical you probably havent heard of them. Yuccie franzen williamsburg slow-carb. Microdosing cliche cray craft beer park tacos wolf pitchfork. Scenester chambray echo lumbersexual chia next level.', 'Montreal', 1, 'https://randomuser.me/api/portraits/men/19.jpg', TRUE),
('norman.sipes@ziemannkovacek.net', 'Destiny', 'password', 40, 941, 'Polaroid fashion axe butcher hoodie keytar swag. Plaid truffaut single-origin coffee chillwave celiac blue bottle umami pickled. Locavore post-ironic bitters hella carry roof. Scenester poutine blue bottle church-key. Butcher meditation master try-hard microdosing.', 'Montreal', 2, 'https://randomuser.me/api/portraits/women/33.jpg', TRUE),
('carl_wuckert@schuppe.net', 'Harvey', 'password', 18, 400, 'Pour-over cardigan pop-up. Celiac hella before they sold out. Listicle tattooed craft beer vhs fixie iphone kale chips. Keffiyeh marfa taxidermy kinfolk actually. Franzen vegan farm-to-table green juice locavore blue bottle etsy. Cronut art party mumblecore microdosing phlogiston.', 'Montreal', 1, 'https://randomuser.me/api/portraits/men/18.jpg', TRUE),
('keenan_langworth@schultzlangworth.info', 'Allison', 'password', 30, 337, 'Cred tote bag chia skateboard wolf irony poutine. Quinoa shoreditch tote bag microdosing hoodie next level. Keffiyeh schlitz pork belly food truck pinterest salvia before they sold out. Forage franzen synth. Cornhole godard distillery retro keffiyeh.', 'Quebec City', 3, 'https://randomuser.me/api/portraits/men/6.jpg', TRUE),
('bryan_kemmer@ritchie.com', 'Michelle', 'password', 29, 783, 'Lumbersexual bicycle rights ugh hammock chillwave. Brunch chambray tacos. Keytar jean shorts cray mustache messenger bag. Helvetica readymade butcher selvage crucifix +1. Slow-carb 8-bit next level.', 'Montreal', 3, 'https://randomuser.me/api/portraits/men/91.jpg', TRUE),
('min@padbergschneider.co', 'Tran', 'password', 38, 464, 'Drinking next level raw denim vinyl chartreuse yr literally sustainable. Celiac forage quinoa polaroid church-key craft beer keffiyeh neutra. Humblebrag migas thundercats schlitz tumblr cliche gentrify. Umami gentrify small batch. Ugh craft beer scenester typewriter cornhole you probably havent heard of them mumblecore mustache.', 'Quebec City', 1, 'https://randomuser.me/api/portraits/men/93.jpg', TRUE),
('domitila@wilderman.io', 'Conrad', 'password', 21, 713, 'Goth occupy bespoke diy bitters green juice. Keffiyeh flexitarian 90s five dollar toast post-ironic wes anderson. Typewriter +1 lumbersexual stumptown. Shabby chic cliche humblebrag wes anderson celiac butcher. Twee mumblecore leggings beard meh kinfolk.', 'Montreal', 2, 'https://randomuser.me/api/portraits/men/40.jpg', TRUE),
('romelia@robel.co', 'Noma', 'password', 32, 889, 'Microdosing helvetica actually thundercats. Poutine lumbersexual phlogiston pbr&b. Schlitz muggle magic vice polaroid. 8-bit tofu paleo everyday swag fixie.', 'Montreal', 1, 'https://randomuser.me/api/portraits/women/80.jpg', TRUE),
('carmine_lebsack@schinner.org', 'Hyacinth', 'password', 19, 706, 'Quinoa occupy sartorial umami. Vice brooklyn cardigan single-origin coffee. Cardigan forage distillery taxidermy goth thundercats small batch. Leggings hashtag chicharrones trust fund scenester meggings drinking 8-bit.', 'Toronto', 1, 'https://randomuser.me/api/portraits/women/88.jpg', TRUE);
