DROP TABLE IF EXISTS genders CASCADE;
DROP TABLE IF EXISTS sexual_preferences CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE genders (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

CREATE TABLE users (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
age INTEGER,
POINTS INTEGER,
bio TEXT,
city VARCHAR(255),
gender_id INTEGER REFERENCES genders,
is_looking BOOLEAN,
image_url TEXT
);

CREATE TABLE sexual_preferences (
id SERIAL PRIMARY KEY,
user_id INTEGER REFERENCES users ON DELETE CASCADE,
gender_id INTEGER REFERENCES genders
);

CREATE TABLE matches (
id SERIAL PRIMARY KEY,
matchmaker_id INTEGER REFERENCES users,
user1_id INTEGER REFERENCES users ON DELETE CASCADE,
user2_id INTEGER REFERENCES users ON DELETE CASCADE,
user1_rating INTEGER,
user2_rating INTEGER
);

